apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: cert-manager-sub.yaml
  target:
    kind: "Subscription"
    name: openshift-cert-manager-operator


