apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    openshift.io/description: Project to host CP4i based applications
    openshift.io/display-name: CP4i
  name: cp4i-dev

