kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4                                                      
storageConfig:                                                      
  registry:
    imageURL: craig.azurecr.io/openshift4                 
    skipTLS: false
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.15  
    packages:
      - name: cluster-logging
        channels:
          - name: stable-5.9
      - name: openshift-gitops-operator
        channels:
          - name: latest
      - name: openshift-cert-manager-operator
        channels:
          - name: stable-v1
      - name: redhat-oadp-operator
        channels:
          - name: stable-1.4
      - name: rhbk-operator
        channels:
          - name: stable-v24
      - name: openshift-pipelines-operator-rh
        channels:
          - name: latest
  additionalImages:
  - name: registry.redhat.io/openshift4/ose-cli:v4.15
  - name: k8s.gcr.io/e2e-test-images/busybox:1.29
  - name: registry.connect.redhat.com/sumologic/busybox:1.36.0-ubi
  helm: 
    repositories:
    - name: craigacr-csi-secrets-store-provider-azure
      url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    - name: craigacr-csi-secrets-store-provider-azure
      url: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
