kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4                                                      
storageConfig:                                                      
  registry:
    imageURL: craig.azurecr.io/openshift4                 
    skipTLS: false
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.17
    packages:
      - name: cluster-logging
        channels:
          - name: stable-6.3
      - name: compliance-operator
        channels:
          - name: stable
      - name: openshift-gitops-operator
        channels:
          - name: latest
      - name: openshift-pipelines-operator-rh
        channels:
          - name: latest
      - name: redhat-oadp-operator
        channels:
          - name: stable-1.4
  additionalImages:
  - name: registry.redhat.io/openshift4/ose-cli:v4.15
  helm: 
    repositories:
    - name: secrets-store-csi-driver
      url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      charts:
        - name: secrets-store-csi-driver
          version: 1.4.6
    - name: csi-secrets-store-driver-provider-azure
      url: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
      charts:
        - name: csi-secrets-store-provider-azure
          version: 1.4.1