apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
spec:
  destination:
    namespace: cert-manager-operator
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: cert-manager/overlays/sno
    repoURL: https://github.com/crscottau/aro-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
