apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oadp-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-adp
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: oadp-operator/overlays/aro
    repoURL: https://github.com/crscottau/aro-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
