apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-logging
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-logging
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: openshift-logging/overlays/aro
    repoURL: https://github.com/crscottau/aro-gitops.git
    targetRevision: t14
  syncPolicy:
    automated: {}
