apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: projects/overlays/non-prod
    repoURL: https://github.com/crscottau/aro-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
