apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml  
- operatorgroup.yaml  
- subscription.yaml
- postgres-db.yaml  
- postgres-service.yaml  
#- keycloak.yaml  
