apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- logging-cluster-log-forwarder.yaml
- logging-cluster-logging.yaml

patches:
- path: patches-logging-sub.yaml
  target:
    kind: Subscription
    name: cluster-logging 
- path: patches-delete-instance-rsyslog.yaml
  target:
    kind: ClusterLogForwarder
    name: instance-rsyslog 

