apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- logging-cluster-log-forwarder.yaml

patches:
- path: patches-logging-sub.yaml
  target:
    kind: "Subscription"
    name: openshift-logging 


