apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"  
spec:
  outputs:
  - name: azure-monitor-app
    type: azureMonitor
    azureMonitor:
      customerId: d8cc13a8-6fb7-4774-8c00-913ea6451718
      logType: aro_application_logs
    secret:
      name: azure-monitor-shared-key
  - name: azure-monitor-infra
    type: azureMonitor
    azureMonitor:
      customerId: d8cc13a8-6fb7-4774-8c00-913ea6451718
      logType: aro_infrastructure_logs
    secret:
      name: azure-monitor-shared-key
  pipelines:
  - name: app-pipeline
    inputRefs:
    - application
    outputRefs:
    - azure-monitor-app
  - name: infra-pipeline
    inputRefs:
    - infrastructure
    outputRefs:
    - azure-monitor-infra