apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: patches-pipelines-sub.yaml
  target:
    kind: "Subscription"
    name: openshift-pipelines-operator 

