apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-store-csi-driver-privileged
  namespace: secrets-store-csi
roleRef:
  apiGroup: security.openshift.io
  kind: SecurityContextConstraints
  name: privileged
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: secrets-store-csi