apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-secrets-store-provider-azure:scc:privileged
  namespace: secrets-store-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: csi-secrets-store-provider-azure
  namespace: secrets-store-csi