apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: openshift-gitops  
spec:
  destination:
    namespace: secrets-store-csi
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    targetRevision: 1.4.6
    chart: secrets-store-csi-driver
  sources: []
  project: default
  syncPolicy:
    automated: {}  