apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-azure
  namespace: openshift-gitops
spec:
  destination:
    namespace: secrets-store-csi
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    targetRevision: 1.4.1
    chart: secrets-store-csi-driver-provider-azure
  sources: []
  project: default
  syncPolicy:
    automated: {}    