apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver-provider-azure
  namespace: openshift-gitops
spec:
  destination:
    namespace: secrets-store-csi
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
    targetRevision: 1.6.0
    chart: secrets-store-csi-driver-provider-azure
    helm:
      parameters:
        - name: linux.privileged
          value: true
        - name: secrets-store-csi-driver.install
          value: false
        - name: linux.providersDir
          value: /var/run/secrets-store-csi-providers    
  sources: []
  project: default
  syncPolicy:
    automated: {}    