apiVersion: v1
kind: LimitRange
metadata:
  name: cp4i-resource-limits
  namespace: cp4i
spec:
  limits:
  - default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 4Mi
    type: Container
